spring.application.name=puzzlegame-backend
server.port=${PORT:8080}


spring.h2.console.enabled=true
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-circular-references=true
spring.flyway.repair=true