#Not in use at the moment. All the properties are configured in application.properties

spring.application.name=SpringShoppingBot
#https://dzcargulkhiobiuhqbhy.supabase.co/puzzle_game
#postgresql://postgres.dzcargulkhiobiuhqbhy:[YOUR-PASSWORD]@aws-1-eu-west-2.pooler.supabase.com:5432/postgres
#postgresql://postgres:[YOUR-PASSWORD]@db.dzcargulkhiobiuhqbhy.supabase.co:5432/postgres
spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}

#cloudinary.folder=Swap-Puzzle-Game-NFT

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false