#Not in use at the moment. All the properties are configured in application.properties

spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false